# Generated by Django 3.2.7 on 2021-09-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_time',
            field=models.CharField(default=0, max_length=50, verbose_name='Send time'),
            preserve_default=False,
        ),
    ]
