# Generated by Django 3.2.7 on 2021-09-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_message_send_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ts',
            field=models.CharField(default=0, max_length=30, verbose_name='Last message index'),
            preserve_default=False,
        ),
    ]
